### ISSUE TITLE
Add goblet unsmelting reciepes.

### ISSUE THREAD

**Issue by DwarfyAssassin** [CraftedMods/nei-lotr#48]
Didn't fill out the whole form because I was lazy. But you can unsmelt goblets and it isn't in NEI.
If you want I can add the recipes
.

**Comment by CraftedMods** [comment]
Can't reproduce that. Works fine for me.

**Comment by DwarfyAssassin** [comment]
It seems to also work for me now. Maybe I just overlooked it yesterday.
