### ISSUE TITLE
Can't get Minecraft to work

### ISSUE THREAD

**Issue by Kennystn2** [CraftedMods/nei-lotr#54]
So I'm a tech noob and I want to play the Lord of the Rings mod.  I got the Lord of the Rings Mod to work with 1.7.10 Forge.  I tried to add NEI 1.7.10 with the Recipe Handlers and LOTR master plugins.  I just dropped the zip/jar files into my Minecraft Mods folder.  Minecraft is now saying that the version of NEI is too old.  What do I do?  (Explain in less technical terms please, I am still learning)

**Comment by CraftedMods** [comment]
This is the wrong place for that, but i'll help you.
I assume you already installed Forge for 1.7.10.
Delete all the mods in your mods folder, and add the following:
* https://www.mediafire.com/file/gltwzjz81se5mgt/
* https://www.curseforge.com/minecraft/mc-mods/nei-lotr/files/2761709
* https://www.curseforge.com/minecraft/mc-mods/nei-recipe-handlers/files/2761077
* https://www.curseforge.com/minecraft/mc-mods/codechickencore/files/2262089
* https://www.curseforge.com/minecraft/mc-mods/notenoughitems/files/2302312

**Comment by CraftedMods** [comment]
Also, for the future, the place for requests like that is at https://lotrminecraftmod.fandom.com/wiki/Board:LotR_Mod_Technical_Support
You can still continue to post in this thread for that specific issue you currently have.
