### ISSUE TITLE
A minor question

### ISSUE THREAD

**Issue by 502y** [CraftedMods/nei-lotr#59]
When I started the game, forge took a long time (about 20 minutes) to load the mod and used all my CPU resources. But in the end, I can enter the game.What should I do?
PS: I guarantee that all mods are up to date.

**Comment by CraftedMods** [comment]
This is actually expected, though the duration is extreme in your case. The LOTR Mod contains the alloy forge recipes in a very NEI-unfriendly way, so I've to extract them with pretty performance intensive methods. Depending on your hardware and mod count, this can take a while (at my old laptop it takes 1 minute, at my new one 20 seconds, but it can vary).
The results are cached, so with future startups (assuming no mods did change), it'll be faster.
If you want to permanentely speed the startup up, you can disable the alloy forge recipe handlers via the configuration file/GUI. If you want more instructions regarding this or have any more questions, just ask.
