### ISSUE TITLE
Map wont load

### ISSUE THREAD

**Issue by Dracovnic** [CraftedMods/nei-lotr#60]
All of the mods load in and I can see the menu, but when I select a world to play as soon as it loads, it brings me back to the main menu after saying "A fatal error has occured, the connection is terminated" after "shutting down my internal server"

#### Minecraft: ####
- NEI LOTR version: 
- MinecraftForge version:
- LOTR Mod version:
- CodeChickenCore version:
- NEI version:
- Optifine and/or Fastcraft installed:
#### Java: #####
- Java version: 
- Allocated memory: 
- Are any other special JVM flags set: 
#### Operating System: ####
- Operating System: mac

**Comment by CraftedMods** [comment]
Can you send me your logs (`fml-client-latest.log`)? For example via pastebin - make sure to censor any personal information those may contain.

**Comment by CraftedMods** [comment]
If you want support for the issue, post the information as specified above.
