### ISSUE TITLE
NEI, CodeChickenCore, and/or any NEI Addons cause a crash. (This is the only somewhat active addon for NEI.)

### ISSUE THREAD

**Issue by MagmaSlime123** [CraftedMods/nei-lotr#64]
### Expected behaviour: ###
The game starting up.

### Actual behaviour: ###
Title.

#### Crash reports: ####
None are created.

#### Screenshots: ####
![image](https://user-images.githubusercontent.com/51277766/115606773-fe4b2b80-a298-11eb-8f7d-cb0c9d2aa60d.png)

### Other things to say: ###
Pretty much anything related to NEI and CodeChickenCore will cause a crash. No reports are given, however, the logs do have a bunch of CodeChickenCore error stuff. Since this is the only active? NEI addon, then this is why I'm putting this here.
Pastebin: https://pastebin.com/fPn1UcK5

#### Minecraft: ####
- NEI LOTR version: neiLotr-1.0.0-BETA.jar
- MinecraftForge version: 1614.
- LOTR Mod version: LOTRMod v36.10
- CodeChickenCore version: CodeChickenCore-1.7.10-1.0.7.47.
- NEI version: NotEnoughItems-1.7.10-1.0.5.120.
- Optifine and/or Fastcraft installed: FastCraft.

#### Java: #####
- Java version: Java 15.
- Allocated memory: 6 GBs.
- Are any other special JVM flags set: CurseForge's defaults.

#### Operating System: ####
- Operating System: Windows 10.

**Comment by CraftedMods** [comment]
You need Java 8 for 1.7.10.

**Comment by MagmaSlime123** [comment]
I had it. Tried Java 15 as well.

**Comment by CraftedMods** [comment]
The error seems to be something with CodeChickenLib, a dependency installed by CodeChickenCore/NEI. Delete the code chicken lib jar in the `mods/1.7.10` directory, and retry (with Java 8).

**Comment by MagmaSlime123** [comment]
Tried that probably 30 times. Literally.

Can't find any Java 8 download that doesn't require an account sign up for the Orcale site thing that Java is from usually.

**Comment by CraftedMods** [comment]
A Java 8 JRE should come bundled with the default MC launcher, you can refer to that. Maybe it's even used, because I would expect the game to crash literally on launch with Java 15, though maybe it already does. Can you send me the full crash report?

**Comment by MagmaSlime123** [comment]
As I said, no reports are given. The logs are the only thing.

**Comment by CraftedMods** [comment]
Then try to get Java 8 to work with the launcher, because I assume Java 15 won't help anything.

**Comment by MagmaSlime123** [comment]
Well, apparently I never had Java 8, somehow. Game runs fine. Just 1.7.10 shits itself.

**Comment by CraftedMods** [comment]
Yes, higher Java versions had changes which are not compatible with Forge or MC for 1.7.10, since those were created/maintained the last time around 2016.

**Comment by MagmaSlime123** [comment]
Ah. Well, I can't find any links anywhere and I'm not gonna deal with making an account to download a bit of software so, not to sound lazy but you mind giving the link?

**Comment by CraftedMods** [comment]
Well, no link, because you indeed need an account, it's quiet a hassle to download it. But your vanilla MC launcher has a Java 8 JRE included (meaning it's somewhere located at your PC), so you can just look it up and refer to it. I can look for the path if you don't find it.

**Comment by MagmaSlime123** [comment]
Yeah, sure.

**Comment by CraftedMods** [comment]
For me it's located at `C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64\bin\java.exe`.

**Comment by MagmaSlime123** [comment]
Found it. Does nothing, though.

Sorry if I'm wasting your time.

**Comment by CraftedMods** [comment]
Can you show a screenshot of your launcher profile config? Also, we can continue this on discord, if you have an account there.

**Comment by MagmaSlime123** [comment]
Yeah, I do. 
Not sure what config your looking for. Cause there's a modding one and another which Idk where to find.
![image](https://user-images.githubusercontent.com/51277766/115611140-93045800-a29e-11eb-98a0-1f042358bc71.png)

**Comment by CraftedMods** [comment]
Alright, I'm Malvegil#1928.

**Comment by MagmaSlime123** [comment]
Sent.

**Comment by MagmaSlime123** [comment]
@CraftedMods Continued & resolved via Discord. Closing.
