### ISSUE TITLE
Only craftingtable crafts

### ISSUE THREAD

**Issue by OrbitFury** [CraftedMods/nei-lotr#66]
Mi problem My problem is that even though I have nei and neilotr (without any complement for the latter) it does not show me the crafting of things that are not achieved through the ordinary crafting table

**Comment by CraftedMods** [comment]
Hello, for that problem please come to my discord server https://discord.gg/37GanUf, where we can help you further. In case you don't have a discord account, we can resolve the issue here.

**Comment by CraftedMods** [comment]
Closes because of no response.
